export type GameMediaKind = 'image' | 'video';

export type GameMedia = {
  id: string;
  kind: GameMediaKind;
  src: string;
  width: number;
  height: number;
  aspectRatio: string;
  alt: string;
  caption: string;
  category: string;
  placements: string[];
  gameBuild: string;
  poster?: string;
  focus?: string;
};

// Generated by scripts/import-game-media.mjs when approved captures are imported.
// Keep this valid and empty until real, public-safe gameplay media has been synced.
export const gameMedia: GameMedia[] = [];

export const mediaFor = (placement: string): GameMedia[] =>
  gameMedia.filter((asset) => asset.placements.includes(placement));

export const firstMediaFor = (placement: string): GameMedia | undefined =>
  mediaFor(placement)[0];
